language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: DKE2BgA1BM2JL3G9jgIzoDJA1G1vnLuRVKLLpdC1gPmOH01Y9eoYerNdKeSkvajzvPL5zR7AL87cS400pN/7bzZMvLYgwFgCQXIcvI5iVxX9wgpGBJs1lsNngihWVBw9v+6jRgfl52aN2w3ng3tlijf/2XwMTWlBJru4wjCMKeqjeQIutDMD+Kc6K9hHPbmfaoL2FoFtDz8q3lBGaSqKn6ofLHajHXgo7/qOWh2deT54qv7XgXFrxdS/PPzVJSHf8dhGadpNAAffC2s+C4N+N7Bo7BE4w227xiIgfeb4RMaL5wwmMJxxj24EQ/G0sRxkaOdXr2EB4OQo1Zre3ZSo/9VVrteRT4fGiVyD0bvb+/QfQpsTx00Yr40G+lIcLI+nfZknD0IEQ4GT8iYH6xQ/qyMvVYUF2j4cBgoo16+9xHA4Ke2jYolIjw4PTvWgg/5u/xUAWOKL8bxFvEa8uUAIDiDvJLy5ygFi71EYUoYaUETQMUj5hWrgRABRdHh5mZJJNGZLL38hwGZfVhsOtVGm3Q9lQcv/8Apf06jYogNmnE22401XlM3Qab5Tf3A2J9b7Ml1HToUl16e8CU77Ss3oEv/gWhMetlyCcIWDVSjuy1kH6q/5vk7zwwsqqxwoUbhhoZLvkhWULljLJkIoEfNrcXU0OkXyONsjUJBATeolRBI=
  app: node-shopping-list-integration-tests
  on:
    repo: jinesh701/node-shopping-list-integration-tests
