language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: 1hnykVGYAOsukzhMfX/8+kxDeSHfbXjc9a2+Ps9+36aV6cp75urLPD2WE0saBK5WdlZsaSaTnKrpCYZUjKyQYdogxCqD/G6FnhfWhapvJaxM7qEtyJeuv9KBScCgmM52eFXGcCrECNZz/R0vmEvgSmSTlRNSt6wDQeoOVYzE7Qc+FzdUG71QIzPhQtABbIRzW/F1l/M87PCM8G4//9VkZ+slsEnX3lnkVtSqHDYw1YXbU+NYCD1aqrwIkeaXrQbya6SH43lPKvMWPXWYgNDMl3CUFV1urWQlbGnVAKvVxXgdr+HW5h4SD7oIKsSI9Nq9spNQUNkQZBiLtjE4nCy9HeNsR4VLgcx3DsgCL2c8/XEej3iOcpm55qV5vU1B8pwkws5l8p4ca3Rm1d4hoN+XgCXFZxgxjAUSoNhwY/7nvtnTzgP2DZ7mOtgt4ARnELjQRR8LTBJPH+wSScdJ9v1/kXDn3CXZBMwA2Bi4XmGpiexTX16lAMugbMsiwKLQgLt7IqE/yZYID+hjrdvkzrkDgfgwgB3nAN8leELmyp3jrEFRjZDcEsMIiVdFi0+SiaIh90HJal3bLdZP07a3jlYC0L4n2Hw5voGMKwJdfGJaqCESwtQNucYgtpD4q5J0iERk9Vxbdwv0wRv8S914+qDQfuJ4QW0MwMa5gh2uzbsmgDY=
  app: dry-temple-14897
  on:
    repo: jinesh701/node-shopping-list-integration-tests
