language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
     secure: "VVhhbN7YD4gwb4o61gjegtQA+uwxw1zzZd3cMziW4fvkspnztkJ7V93J7ZevzqNPJrZL/oiduUb/OaS3+IxmS4+2J8bT1oSRmBL1V0BfSHPYyJrQan1+jvFZWG55Rh6xqlImOaAx4uCY673G2NIa1znTfYj5MPzPKIJ0vv0hRPNU1jjEADBDz86IT97QyeZ/BD8hi3HLWUelmgBYhRYUdRQ4us+8anQUaOFp/q0jTkWmxU9jk/yN01ZfjPwhaQsodQkUxOX5aALWrk9kthiAS54bev+kdbQeRUE5YGuzdBluder2ojJw4MN3fna1oVHPvaNoxcuScXt++4IgtW6Jmbpn/BfN+0Gk8hGnIQFN4gJHotZKEoyJBWUVIDRzice4cJNN7F+DNUBrtOeGqgIJfxKlq5XNI7P64a1eH9KFpUQO603/3W+JTnJn164Qx2j9q65Avd94gl84kPRnfsZxFPMFCT6S8Yf4sL5jxDDomh6NACHZgQ1cbGBn635LYe6mf8SEhg/q863vhemBt74Cty+1/eKnqzZjNRn7cyQU9OpnkQ2CwcBX7I0QZgqSbNO59eW7lHJgNBZuSVOXqbeZa9ANaDOaRMYMh4RvsSi60GFI0rK8JRO6bxpmTLqcS096daULTiGPu7yHGi0pYjJ1ja+whcgKsBZLvzhL0qysLiY="
  app: ancient-harbor-69260
  on:
    repo: jinesh701/node-shopping-list-integration-tests
